Las carreras ahora están ordenadas por nombre
unahur-turnos/backend pull request #38
Opened 2021-02-21 19:34 UTC by CabreraTiago

## :dart: Objetivo

Closes unahur-covid/planificacion#84

## :memo: Comentarios adicionales

Se agrega un gif para verificar que en el frontend el selector de carreras las muestra ordenadas.

## :stop_sign: Requisitos mínimos para pasar la review

- [x] El código tiene tests que prueban la nueva funcionalidad o que el defecto se corrigió

En el caso en que se haya modificado o creado alguna tabla de la base:
- [ ] Se agregaron las migraciones necesarias, con su `up` y `down` completos.
- [ ] Se actualizó el modelo para reflejar los cambios.

## :camera_flash: Capturas de pantalla / GIFs

![carreras_ordenadas](https://user-images.githubusercontent.com/48968913/108636194-7bf1e700-7462-11eb-94da-b6f449762bac.gif)

2021-02-21 21:24 UTC, faloi requested changes
Modificá el test y mergeamos.

2021-02-21 21:24 UTC, faloi commented on lib/controllers/carreras_controller.test.js
> +      const response = await request.get('/api/carreras');
No está bueno que los tests le peguen a la API Guaraní verdadera. Mockeá lo que devuelve como hicimos en el test de API Guaraní, y después te fijás que el controller lo ordene.

2021-02-21 21:24 UTC, faloi commented on lib/controllers/carreras_controller.js
> +  const carrerasOrdenadas = sortWith(
Si tenés un solo criterio para ordenar, usá `sortBy` que no espera una lista como primer parámetro.

2021-02-21 21:24 UTC, faloi commented on lib/controllers/carreras_controller.test.js
> +      const response = await request.get('/api/carreras');
Otra opción es mover el código que ordena al ApiGuarani y testear directamente el `getCarreras`.

2021-02-24 03:52 UTC, CabreraTiago commented
Ya están los cambios, igual te hago una consulta: ¿te parece agregarle todas las carreras al test o con 10 va bien?

2021-02-24 12:11 UTC, faloi approved these changes

2021-02-24 12:11 UTC, faloi commented on lib/helpers/api_guarani.js
> +      compose(toLower, prop('nombre')),
😍

2021-02-24 12:14 UTC, faloi commented
> Ya están los cambios, igual te hago una consulta: ¿te parece agregarle todas las carreras al test o con 10 va bien?

Con 3 carreras ya hubiera estado bien, lo que vos estás probando es que el método las ordena, no importa cuántas sean. Lo que yo hubiera hecho es que el valor mockeado venga desordenado, para validar que efectivamente el método las ordena... de hecho es lo que pasa ahora: la API lo devuelve así. 

El test que está ahora pasaría incluso sin el `sortBy`, porque el juego de datos que armaste ya está ordenado.

2021-02-24 12:17 UTC, merged

2021-02-24 12:18 UTC, faloi commented on lib/helpers/api_guarani.test.js
> -          {
@CabreraTiago fijate ahí, las desordené a propósito y el test pasa porque la implementación está bien.