Envio de mail registro usuario
unahur-turnos/backend pull request #51
Opened 2021-03-15 03:48 UTC by CabreraTiago

## :dart: Objetivo

Closes unahur-turnos/planificacion#95

## :memo: Comentarios adicionales

No encontré la manera de insertar el logo de la app en el correo. Intenté con `app.use(express.static('public'))` y con `app.use('/images', express.static('images'))` pero no hubo caso. 

## :stop_sign: Requisitos mínimos para pasar la review

- [x] El código tiene tests que prueban la nueva funcionalidad o que el defecto se corrigió

En el caso en que se haya modificado o creado alguna tabla de la base:
- [ ] Se agregaron las migraciones necesarias, con su `up` y `down` completos.
- [ ] Se actualizó el modelo para reflejar los cambios.

## :camera_flash: Capturas de pantalla / GIFs

![Mail#1](https://user-images.githubusercontent.com/48968913/111101117-fffe3280-8527-11eb-8758-421f8bd69357.png)

![Mail#2](https://user-images.githubusercontent.com/48968913/111101127-02f92300-8528-11eb-8078-922854c41c90.png)

2021-03-15 21:43 UTC, faloi requested changes
Muy buen laburo.
De denso nomás, probaría cómo se ve usando fondo blanco. Creo que la Card destacaría más si el fondo es de un solo color y claro.

2021-03-15 21:43 UTC, faloi commented on .env.example
> +MAIL_AUTH_PASSWORD=7uRn0$.1734
Los datos sensibles nunca se comitean. En este caso, como son credenciales, el example queda vacío.

2021-03-15 21:43 UTC, faloi commented on lib/controllers/usuario_controller.test.js
> +      expect(MailSender.sendMail.mock.calls.length).toBeLessThanOrEqual(1);
Acá podrías testear que le mandó los parámetros correctos. Al menos el mail y el subject, el body ya sería demasiado difícil de entender qué pasó si falla.

2021-03-15 21:43 UTC, faloi commented on lib/controllers/usuario_controller.test.js
> +      expect(MailSender.sendMail.mock.calls.length).toBeLessThanOrEqual(2);
Si ya probaste arriba y este es el mismo caso, lo sacaría.

2021-03-15 21:43 UTC, faloi commented on lib/controllers/usuario_controller.test.js
> +      expect(MailSender.sendMail.mock.calls.length).toBeLessThanOrEqual(1);
Además estaría bueno que sea otro `it`, cosa de que si falla se note rápido que lo que no anda es el envío de mail.

2021-03-15 21:43 UTC, faloi commented on lib/helpers/mail_sender.js
> +    html: html,
Un detalle pavo, cuando la clave se llama igual que el parámetro/variable/const, se puede omitir:


```suggestion
    subject,
    html,
```

2021-03-15 21:43 UTC, faloi commented on lib/html/templateRegistro.html
> +                <!-- <img
Una URL relativa no te va a andar, porque va a tomar como host al dominio desde el cual estés abriendo el mail.

Opciones:
1) poner una URL absoluta,
2) convertir el logo a Base64 y tirarlo acá nomás.

Yo iría por la segunda.

2021-03-15 21:43 UTC, faloi commented on lib/html/templateRegistro.html
> +                              href="https://turnos.unahur.edu.ar/login"
Ok, aunque no es muy prolijo hardcodear la URL. Ideal sería lo que te decía más arriba de tener el host en una variable de entorno.

2021-03-15 21:43 UTC, faloi commented on lib/models/usuario.js
> -    // directamente le pone los puntos en el nombre del atributo.
Estos comentarios los puse a propósito, porque alguien que lee el código podría no entender por qué se hizo así. No lo borraría.

2021-03-15 21:43 UTC, faloi commented on lib/utils/html_utils.js
> +  const source = await ejs.renderFile(path, data);
Muy buena idea usar esto para meter variables en el HTML. :clap:

2021-03-15 21:43 UTC, faloi commented on lib/html/templateRegistro.html
> +                <!-- <img
La ventaja de la segunda es que el mail ya contiene todo, incluso si se cayera nuestra app o lo que sea, el logo ya estaría embebido en el mail.

2021-03-16 00:27 UTC, CabreraTiago commented on lib/models/usuario.js
> -    // directamente le pone los puntos en el nombre del atributo.
Mala mía, sorry.

2021-03-16 00:38 UTC, clombardi commented
Prueben raw: true, nest: true, tal vez les sirva.

On Mon, Mar 15, 2021 at 9:27 PM CabreraTiago ***@***.***>
wrote:

> *@CabreraTiago* commented on this pull request.
> ------------------------------
>
> In lib/models/usuario.js
> <https://github.com/unahur-turnos/backend/pull/51#discussion_r594779253>:
>
> > -    // Al usar raw, Sequelize ni se molesta en crear objetos anidados:
>
> -    // directamente le pone los puntos en el nombre del atributo.
>
>
> Mala mía, sorry.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/unahur-turnos/backend/pull/51#discussion_r594779253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABKDRL7BUGR3WE6LTQZ42VDTD2QXJANCNFSM4ZFXYO4Q>
> .
>

2021-03-16 22:14 UTC, CabreraTiago commented on lib/html/templateRegistro.html
> +                <!-- <img
Al parecer Gmail no se banca las imágenes en Base64.

2021-03-16 22:15 UTC, CabreraTiago commented
![mail_modo_claro#1](https://user-images.githubusercontent.com/48968913/111387014-d6f6b280-868b-11eb-80d3-b3d6eb86911e.png)

![mail_modo_claro#2](https://user-images.githubusercontent.com/48968913/111387031-de1dc080-868b-11eb-8633-708b4e254844.png)

![mobile_claro#1](https://user-images.githubusercontent.com/48968913/111387064-ea098280-868b-11eb-988e-485375768b19.jpg)

![mobile_claro#2](https://user-images.githubusercontent.com/48968913/111387127-fe4d7f80-868b-11eb-9b49-1d2b616420c8.jpg)

2021-03-16 22:17 UTC, CabreraTiago commented
![mail_modo_oscuro#1](https://user-images.githubusercontent.com/48968913/111387174-132a1300-868c-11eb-9730-bcab98c3ffdb.png)

![mail_modo_oscuro#2](https://user-images.githubusercontent.com/48968913/111387192-18875d80-868c-11eb-8b1b-4e38b5dd1b57.png)

![mobile_oscuro](https://user-images.githubusercontent.com/48968913/111387237-289f3d00-868c-11eb-9cb8-2866e991d16f.jpg)

2021-03-17 00:55 UTC, faloi approved these changes

2021-03-17 00:55 UTC, faloi commented on lib/controllers/usuario_controller.test.js
> +      expect(MailSender.sendMail.mock.calls[2]).toEqual(
Hay una más fácil, tipo `expect(MailSender.sendMail).toHaveBeenCalledWith(arg1, arg2, etc)`. Ya fue igual, queda para la próxima.

2021-03-17 00:55 UTC, faloi commented on .env.example
> +TURNOS_UNAHUR_URL=https://turnos.unahur.edu.ar/login
Para la próxima también: lo que yo sugería era poner en variable de entorno únicamente la URL base del host, se suele hacer bastante para casos como este: tenés el host y luego le appendeás lo que quieras.

2021-03-17 00:55 UTC, faloi commented on .env.example
> +TURNOS_UNAHUR_AYUDA=http://www.unahur.edu.ar/es/ya-se-pueden-reservar-computadoras-para-estudiar-traves-de-turnos-online
Esta no me molestaba que estuviera hardcodeada, porque no va a cambiar aunque cambie la URL de esta app. Pero fue también.

2021-03-22 19:34 UTC, merged