2 Turnos por día
unahur-turnos/backend pull request #55
Opened 2021-03-24 00:05 UTC by AyelenRdgz

Closes unahur-turnos/planificacion#121

## :memo: 
Se moficó sacarTurnoPara(), con test incluidos.

Falta la parte del front que va con otro PR.

2021-03-24 00:38 UTC, AyelenRdgz commented
Fede, revisamos esto porque nos parecio raro que genere este error, pero es un problema del package.json que no sabemos que es lo que se modifico o porque, es cuestión de ignorar ese archivo para el merge, intentamos varias formas para arreglarlo pero no nos queremos enroscar mas y perder tiempo en esto.

2021-03-24 00:55 UTC, faloi commented on package-lock.json
> +>>>>>>> 959f8bea38d9da644f10cc45d08c191376f39ee3
Acá está el problema, les dio un conflicto y no lo resolvieron bien. 

Hagan lo siguiente: 
1. Borren este archivo `package-lock.json`.
2. Tiren un `npm install`.
3. Commiteen el nuevo `package-lock.json` que se genera.
4. Pusheen.

2021-03-24 01:02 UTC, faloi requested changes

2021-03-24 01:02 UTC, faloi commented on lib/models/usuario.js
> +    let formatDate = JSON.stringify(fechaActividad).replace(/['"]+/g, '');
No entiendo acá por qué hicieron esto, cuentenmé a ver cómo podemos mejorarlo.

2021-03-24 01:02 UTC, faloi commented on lib/models/usuario.js
> -    // directamente le pone los puntos en el nombre del atributo.
No borren esto, lo puse porque el código de abajo puede ser complicado de entender.

2021-03-24 01:02 UTC, faloi commented on lib/utils/dateUtils.js
> +export const formatISO = (fecha) => {
Pareciera que no la usaron. De todos modos, es raro lo que hace: parsea una fecha en formato ISO y luego la vuelve a convertir al mismo formato. 🤔

2021-03-24 01:11 UTC, AyelenRdgz commented on lib/models/usuario.js
> +    let formatDate = JSON.stringify(fechaActividad).replace(/['"]+/g, '');
porque no podiamos hacer que funcione esa fecha que le pasabamos a getInicioDelDia, debugueando nos dimos cuenta que es porque uno venia con comillas simples y otro con dobles, esa linea es para que reemplaze unas comillas con otras y lo pueda entender en el formato que quiere.

2021-03-24 01:11 UTC, AyelenRdgz commented on lib/models/actividad.test.js
> +    it('cuando saca 2 turnos en un dia', async () => {
oki, borro este entonces

2021-03-24 01:12 UTC, AyelenRdgz commented on lib/models/usuario.js
> -    // directamente le pone los puntos en el nombre del atributo.
Si perdon, no sabemos en que momento voló

2021-03-24 01:13 UTC, AyelenRdgz commented on lib/utils/dateUtils.js
> +export const formatISO = (fecha) => {
Ah si, fue una de las tantas pruebitas. Ya esta volando.

2021-03-27 00:18 UTC, AyelenRdgz commented
Fede quisimos arreglar lo del package-lock.json pero ahora genera conflicto de nuevo, va, no sabemos si se había arreglado porque después de tocar vimos que también lo habías tocado o capaz fue por el merge de lo de los chicos. **Disculpas**

2021-04-09 00:08 UTC, faloi approved these changes

2021-04-09 00:08 UTC, merged